apiVersion: apps/v1
kind: Deployment
metadata:
  name: epic-chat
  labels:
    app: epic-chat
spec:
  selector:
    matchLabels:
      app: epic-chat
  replicas: 1
  template:
    metadata:
      labels:
        app: epic-chat
    spec:
      containers:
        - name: front-server2
          image: front-service:v1
          ports:
            - containerPort: 80
        - name: mid-service2
          image: mid-service:v1
          ports:
            - containerPort: 5000
        - name: auth-service2
          image: auth-service:v1
          ports:
            - containerPort: 5001
        - name: noth-service2
          image: noth-service:v1
          ports:
            - containerPort: 5002
        - name: epic-mid-mongo2
          image: mongo
          ports:
            - containerPort: 27017
        - name: epic-noth-mongo2
          image: mongo
          ports:
            - containerPort: 8000
              hostPort: 8000
        - name: epic-auth-mongo2
          image: mongo
          ports:
            - containerPort: 6000
              hostPort: 6000

---
apiVersion: v1
kind: Service
metadata:
  name: epic-chat
  labels:
    app: epic-chat
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: epic-chat

---
apiVersion: v1
kind: Pod
metadata:
  name: epic-chat
  labels:
    app: epic-chat
spec:
  containers:
    - name: front-server2
      image: front-service:v1
      ports:
        - containerPort: 80
    - name: mid-service2
      image: mid-service:v1
      ports:
        - containerPort: 5000
    - name: auth-service2
      image: auth-service:v1
      ports:
        - containerPort: 5001
    - name: noth-service2
      image: noth-service:v1
      ports:
        - containerPort: 5002
    - name: epic-mid-mongo2
      image: mongo
      ports:
        - containerPort: 27017
    - name: epic-noth-mongo2
      image: mongo
      ports:
        - containerPort: 27017
          hostPort: 8000
    - name: epic-auth-mongo2
      image: mongo
      ports:
        - containerPort: 27017
          hostPort: 6000